import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:leger_manager/Components/app_colors.dart';
import 'package:leger_manager/Controller/billing_controller.dart';
import 'package:leger_manager/view/master_page/master_page_pages/Inventory_Module/Billing_Components/inventory_data.dart';

class SmallInvoice extends StatelessWidget {
  final List<InventoryData> dataList;
  final String customerName;
  final String customerInfo;

  SmallInvoice(
      {required this.dataList,
      required this.customerName,
      required this.customerInfo});

  BillingController billingcontroller = Get.put(BillingController());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Container(
          height: 210,
          width: 300,
          child: Container(
            height: 10,
            width: 10,
            color: Colors.white,
            child: Column(
              children: [
                Text(
                  "${customerName}",
                  style: TextStyle(fontSize: 5),
                ),
                Text(
                  "${customerInfo}",
                  style: TextStyle(fontSize: 5),
                ),
                Text(
                  "Invoice",
                  style: TextStyle(fontSize: 5),
                ),
                Text(
                  "Generated by Ledger Manager",
                  style: TextStyle(fontSize: 5),
                ),
                Text(
                  "Date : " + DateFormat('d/M/yyyy').format(DateTime.now()),
                  style: TextStyle(fontSize: 5),
                ),
                Divider(),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    Text(
                      "Item",
                      style: TextStyle(fontSize: 5),
                    ),
                    Text(
                      "Company",
                      style: TextStyle(fontSize: 5),
                    ),
                    Text(
                      "Category",
                      style: TextStyle(fontSize: 5),
                    ),
                    Text(
                      "Product",
                      style: TextStyle(fontSize: 5),
                    ),
                    Text(
                      "Quantity",
                      style: TextStyle(fontSize: 5),
                    ),
                    Text(
                      "Price",
                      style: TextStyle(fontSize: 5),
                    ),
                  ],
                ),
                Divider(),
                Container(
                  decoration: BoxDecoration(
                    color: AppColors.whiteColor,
                    borderRadius: BorderRadius.circular(20),
                  ),
                  height: 120,
                  child: ListView.builder(
                    itemCount: dataList.length,
                    itemBuilder: (context, index) {
                      return ListTile(
                        title: Expanded(
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                            children: [
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    "${index + 1}",
                                    style: TextStyle(fontSize: 8),
                                  ),
                                ],
                              ),
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    "${dataList[index].abc}",
                                    style: TextStyle(fontSize: 8),
                                  ),
                                ],
                              ),
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    "${dataList[index].category}",
                                    style: TextStyle(fontSize: 5),
                                  ),
                                ],
                              ),
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    "${dataList[index].product}",
                                    style: TextStyle(fontSize: 5),
                                  ),
                                ],
                              ),
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    "1",
                                    style: TextStyle(fontSize: 5),
                                  ),
                                ],
                              ),
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.end,
                                children: [
                                  Text(
                                    "${dataList[index].quantity}",
                                    style: TextStyle(fontSize: 5),
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                      );
                    },
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
