import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:leger_manager/Components/elevated_button.dart';
import 'package:leger_manager/view/master_page/master_page_pages/Inventory_Module/Billing_Components/inventory_data.dart';

class ViewInvoice extends StatelessWidget {
  final List<InventoryData> dataList;
  final double amount;
  final String date;

  ViewInvoice(
      {required this.dataList, required this.amount, required this.date});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            color: Colors.white,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  "Namra",
                  style: TextStyle(fontSize: 20),
                ),
                Text(
                  "Invoice",
                  style: TextStyle(fontSize: 15),
                ),
                Text(
                  "Generated by Ledger Manager",
                  style: TextStyle(fontSize: 15),
                ),
                Text(
                  "Date : " + DateFormat('d/M/yyyy').format(DateTime.now()),
                  style: TextStyle(fontSize: 15),
                ),
                SizedBox(height: 10),
                Table(
                  defaultColumnWidth: FixedColumnWidth(50.0),
                  children: [
                    TableRow(
                      children: [
                        Divider(),
                        Divider(),
                        Divider(),
                        Divider(),
                        Divider(),
                        Divider(),
                      ],
                    ),
                    TableRow(
                      children: [
                        TableCell(
                          child: Center(
                            child: Text(
                              'Item',
                              style: TextStyle(fontSize: 10),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Center(
                            child: Text(
                              'Company',
                              style: TextStyle(fontSize: 10),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Center(
                            child: Text(
                              'Category',
                              style: TextStyle(fontSize: 10),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Center(
                            child: Text(
                              'Product',
                              style: TextStyle(fontSize: 10),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Center(
                            child: Text(
                              'Quantity',
                              style: TextStyle(fontSize: 10),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Center(
                            child: Text(
                              'Price',
                              style: TextStyle(fontSize: 10),
                            ),
                          ),
                        ),
                      ],
                    ),
                    TableRow(
                      children: [
                        Divider(),
                        Divider(),
                        Divider(),
                        Divider(),
                        Divider(),
                        Divider(),
                      ],
                    ),
                    TableRow(
                      children: [
                        SizedBox(
                          height: 10,
                        ),
                        SizedBox(),
                        SizedBox(),
                        SizedBox(),
                        SizedBox(),
                        SizedBox(),
                      ],
                    ),
                    for (int index = 0; index < dataList.length; index++)
                      TableRow(
                        children: [
                          TableCell(
                            child: Center(
                              child: Text(
                                '${index + 1}',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Center(
                              child: Text(
                                '${dataList[index].abc}',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Center(
                              child: Text(
                                '${dataList[index].category}',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Center(
                              child: Text(
                                '${dataList[index].product}',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Center(
                              child: Text(
                                '${dataList[index].quantity}',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Center(
                              child: Text(
                                '${dataList[index].total_price}',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                        ],
                      ),
                  ],
                ),
                Divider(),
                Padding(
                  padding: const EdgeInsets.only(left: 55.0, right: 55.0),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text("Total"),
                      Text(
                        "${amount}",
                      ),
                    ],
                  ),
                )
              ],
            ),
          ),
          SizedBox(
            height: 20,
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              CustomButton(buttonText: "Save as PDF", onPressed: () {}),
              CustomButton(buttonText: "Whatsapp", onPressed: () {}),
            ],
          ),
        ],
      ),
    );
  }
}
