// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bclfMkS7z9jTZvLXCCJZrWtoVMdV73g',
    appId: '1:79519647699:web:47aa3a4775e9a8118f5126',
    messagingSenderId: '79519647699',
    projectId: 'hcdproject-c4932',
    authDomain: 'hcdproject-c4932.firebaseapp.com',
    storageBucket: 'hcdproject-c4932.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDag27XrH0FbGchHNGuNKegMjltFACX_wA',
    appId: '1:79519647699:android:f200f9c012d7a98e8f5126',
    messagingSenderId: '79519647699',
    projectId: 'hcdproject-c4932',
    storageBucket: 'hcdproject-c4932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeF2VEZL7qH_mCm-8O8wX9k76aNnJAPlw',
    appId: '1:79519647699:ios:4b8d0cc6fca030138f5126',
    messagingSenderId: '79519647699',
    projectId: 'hcdproject-c4932',
    storageBucket: 'hcdproject-c4932.appspot.com',
    iosBundleId: 'com.example.legerManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeF2VEZL7qH_mCm-8O8wX9k76aNnJAPlw',
    appId: '1:79519647699:ios:6010b42be7ead20b8f5126',
    messagingSenderId: '79519647699',
    projectId: 'hcdproject-c4932',
    storageBucket: 'hcdproject-c4932.appspot.com',
    iosBundleId: 'com.example.legerManager.RunnerTests',
  );
}
