// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGbtJI0IKv8fqkjeASVCrFNkW0UmIGFSk',
    appId: '1:326509409836:web:f2249e343e9ec713adc389',
    messagingSenderId: '326509409836',
    projectId: 'ledgermanager-7395f',
    authDomain: 'ledgermanager-7395f.firebaseapp.com',
    storageBucket: 'ledgermanager-7395f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbs25xESo0gOfAgd_Xmmfepd6OihhgTUQ',
    appId: '1:326509409836:android:1809d904bc0630a8adc389',
    messagingSenderId: '326509409836',
    projectId: 'ledgermanager-7395f',
    storageBucket: 'ledgermanager-7395f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBve2E95qR7Q3C429ZEvCaWL-7ee0fI9-g',
    appId: '1:326509409836:ios:bd2e8a9e8d958e1aadc389',
    messagingSenderId: '326509409836',
    projectId: 'ledgermanager-7395f',
    storageBucket: 'ledgermanager-7395f.appspot.com',
    iosBundleId: 'com.example.legerManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBve2E95qR7Q3C429ZEvCaWL-7ee0fI9-g',
    appId: '1:326509409836:ios:bd2e8a9e8d958e1aadc389',
    messagingSenderId: '326509409836',
    projectId: 'ledgermanager-7395f',
    storageBucket: 'ledgermanager-7395f.appspot.com',
    iosBundleId: 'com.example.legerManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGbtJI0IKv8fqkjeASVCrFNkW0UmIGFSk',
    appId: '1:326509409836:web:c8d9ce4cc0db7c5aadc389',
    messagingSenderId: '326509409836',
    projectId: 'ledgermanager-7395f',
    authDomain: 'ledgermanager-7395f.firebaseapp.com',
    storageBucket: 'ledgermanager-7395f.appspot.com',
  );
}
