import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:leger_manager/Components/app_colors.dart';
import 'package:leger_manager/Controller/billing_controller.dart';
import 'package:leger_manager/view/master_page/master_page_pages/Inventory_Module/Billing_Components/inventory_data.dart';

class Invoice extends StatelessWidget {
  final List<InventoryData> dataList;

  Invoice({required this.dataList});

  BillingController billingcontroller = Get.find<BillingController>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          height: 1000,
          child: Center(
            child: Container(
              height: 400,
              width: 300,
              color: Colors.white,
              child: Column(
                children: [
                  Text(
                    "Namra",
                    style: TextStyle(fontSize: 20),
                  ),
                  Text(
                    "Invoice",
                    style: TextStyle(fontSize: 15),
                  ),
                  Text(
                    "Generated by Ledger Manager",
                    style: TextStyle(fontSize: 15),
                  ),
                  Text(
                    "Date : " + DateFormat('d/M/yyyy').format(DateTime.now()),
                    style: TextStyle(fontSize: 15),
                  ),
                  SizedBox(height: 10),
                  Table(
                    defaultColumnWidth: FixedColumnWidth(50.0),
                    children: [
                      TableRow(
                        children: [
                          Divider(),
                          Divider(),
                          Divider(),
                          Divider(),
                          Divider(),
                          Divider(),
                        ],
                      ),
                      TableRow(
                        children: [
                          TableCell(
                            child: Center(
                              child: Text(
                                'Item',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Center(
                              child: Text(
                                'Company',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Center(
                              child: Text(
                                'Category',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Center(
                              child: Text(
                                'Product',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Center(
                              child: Text(
                                'Quantity',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Center(
                              child: Text(
                                'Price',
                                style: TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                        ],
                      ),
                      TableRow(
                        children: [
                          Divider(),
                          Divider(),
                          Divider(),
                          Divider(),
                          Divider(),
                          Divider(),
                        ],
                      ),
                      TableRow(
                        children: [
                          SizedBox(
                            height: 10,
                          ),
                          SizedBox(),
                          SizedBox(),
                          SizedBox(),
                          SizedBox(),
                          SizedBox(),
                        ],
                      ),
                      for (int index = 0; index < dataList.length; index++)
                        TableRow(
                          children: [
                            TableCell(
                              child: Center(
                                child: Text(
                                  '${index + 1}',
                                  style: TextStyle(fontSize: 10),
                                ),
                              ),
                            ),
                            TableCell(
                              child: Center(
                                child: Text(
                                  '${dataList[index].abc}',
                                  style: TextStyle(fontSize: 10),
                                ),
                              ),
                            ),
                            TableCell(
                              child: Center(
                                child: Text(
                                  '${dataList[index].category}',
                                  style: TextStyle(fontSize: 10),
                                ),
                              ),
                            ),
                            TableCell(
                              child: Center(
                                child: Text(
                                  '${dataList[index].product}',
                                  style: TextStyle(fontSize: 10),
                                ),
                              ),
                            ),
                            TableCell(
                              child: Center(
                                child: Text(
                                  '${dataList[index].quantity}',
                                  style: TextStyle(fontSize: 10),
                                ),
                              ),
                            ),
                            TableCell(
                              child: Center(
                                child: Text(
                                  '${dataList[index].total_price}',
                                  style: TextStyle(fontSize: 10),
                                ),
                              ),
                            ),
                          ],
                        ),
                    ],
                  ),
                  Divider(),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text("Total"),
                      Text(
                        "${billingcontroller.calculateTotalPrice(dataList)}",
                      ),
                    ],
                  )
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
